services:
  - type: web
    name: haospeedtest
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --workers 2 --threads 2 --timeout 120 --keep-alive 5 --log-level info app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GUNICORN_CMD_ARGS
        value: "--timeout 120 --keep-alive 5"
    healthCheckPath: /
    autoDeploy: true 