services:
  - type: web
    name: haospeedtest
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --workers 1 --threads 1 --timeout 30 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true 